version: '3.8'

services:
  mongo_container:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    command: ["mongod", "--replSet", "rs0"] # Enable replication
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
